Fix problems in zvol_set_volmode_impl
openzfs/zfs pull request #11199
Opened 2020-11-12 22:28 UTC by mattmacy

- Don't leave fstrans set when passed a snapshot
 - Don't remove minor if volmode already matches new value
 - (FreeBSD) Wait for GEOM ops to complete before trying
   remove (at create time GEOM will be "tasting" in parallel)

Signed-off-by: Matt Macy <mmacy@FreeBSD.org>

### Motivation and Context

### Description

### How Has This Been Tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2020-11-13 00:33 UTC, freqlabs approved these changes

2020-11-13 00:39 UTC, freqlabs requested changes

2020-11-13 00:39 UTC, freqlabs commented on module/zfs/zvol.c
> +	old_volmode = zv->zv_volmode;
We're going to need to set zv_volmode on Linux somewhere.

2020-11-13 20:46 UTC, freqlabs approved these changes

2020-11-17 17:12 UTC, behlendorf approved these changes

2020-11-17 17:50 UTC, merged