Add -u option to 'zfs create'
openzfs/zfs pull request #11254
Opened 2020-11-30 18:24 UTC by freqlabs

### Motivation and Context

This was reported as a feature lost in FreeBSD with the switch to OpenZFS.

### Description

Add -u option to 'zfs create' that prevents file system from being
automatically mounted. This is similar to the 'zfs receive -u'.

### How Has This Been Tested?

This has been in FreeBSD since 2012. ZTS results pending.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2020-11-30 19:28 UTC, allanjude approved these changes
Reviewed By: Allan Jude <allanjude@freebsd.org>

2020-11-30 22:27 UTC, behlendorf requested changes
Can you include a simple `cli_root/zfs_create/` test for this.

2020-11-30 22:27 UTC, behlendorf commented on cmd/zfs/zfs_main.c
> +		    "used when creating a file system\n"));
nit: It looks like all but a few of the error message use "filesystem" instead of "file system".

2020-11-30 22:27 UTC, behlendorf commented on cmd/zfs/zfs_main.c
> +		ret = zfs_mount_and_share(g_zfs, argv[0], ZFS_TYPE_DATASET);
Skipping the `zfs_mount_and_share` here looks like it will incorrectly leave the return value `ret` as `1`.

2020-12-01 16:26 UTC, freqlabs commented
* s/file system/filesystem/ in error message
* Set ret=0 if nomount
* Add a test

2020-12-01 18:11 UTC, behlendorf approved these changes

2020-12-02 17:24 UTC, behlendorf commented
It seems there's some trouble with the new test:

```
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_nomount (run as root) [00:00] [FAIL]
17:25:22.45 ASSERTION: zfs create -u leaves the new file system unmounted
17:25:22.47 SUCCESS: zfs create -u testpool/testfs1
17:25:22.47 SUCCESS: create_dataset testpool/testfs1 -u
17:25:22.48 SUCCESS: ismounted testpool/testfs1 exited 1
17:25:22.49 ERROR: zfs create -V 150m -u testpool/testvol1 exited 2
```

2020-12-04 22:01 UTC, merged