Decoupling arc_tempreserve_space() and arc_c
openzfs/zfs pull request #12005
Opened 2021-05-06 00:41 UTC by jxdking

Under memory pressure, arc_c often shrinks to a point that
arc_tempreserve_space() fails, and txg is forced to be synced prematurely.
This is especially true for low memory system.

This commit added a new turnable parameter zfs_arc_dirty_max.
It is a fixed value in bytes. The total anon data is compared with this
value in arc_tempreserve_space().

Signed-off-by: jxdking <lostking2008@hotmail.com>

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2021-05-13 18:29 UTC, amotin requested changes
While I also don't like the specified code for the huge I/O delays it introduces, which should much softer be handled by dmu_tx_delay() mechanism rather than waiting for TXG commit, I think you are solving wrong problem.  Situations when the amount of dirty data is bigger than target ARC size are just insane, since you simply have no memory to handle so big transaction group and more frequent commit is the only way. Whether the 50%, 25% and 20% limits are perfect could be discussed, but in proper setup in my believe they should not be reached ever.

The real problem I see in proper (may be more complicated/dynamic) tuning of zfs_dirty_data_max.  Right now it magically scales with amount of total system RAM and applies per pool.  But really it should represent maximum pool throughput for the period of several TXGs.  And system _must_ have sufficient ARC to cover that.  May be we should investigate relations of zfs_arc_min, zfs_dirty_data_max and multiple pools, either statically or in run time.  Or may be have zfs_dirty_data_max per-pool, scaling with average TXG size v/s commit time to avoid excessive write caching (like if you have boot pool USB stick in server with 256GB of RAM), but limited to amount of available memory in your memory-limited scenarios.

2021-05-14 02:48 UTC, jxdking commented
To be more specific, this only becomes a problem for small memory system with 8G memory or below. I know it is not recommended to run zfs less than 8G. It can be a low cost vm node or an embedded system. 
By default, for linux, zfs_dirty_data_max is 10% of memory. I tested, the possible anon data size in ARC could grow 2 times of zfs_dirty_data_max. That is 20% of memory. Before this patch, arc_tempreserve_space() will failed once total anon data exceed 50% of arc_c. That means the arc_c should at least above 40% of total memory to avoid failing. 

For a small memory system, it is really hard to keep 40% of memory available for ARC.

2021-05-14 02:58 UTC, amotin commented
> For a small memory system, it is really hard to keep 40% of memory available for ARC.

Then reduced even lower zfs_dirty_data_max should force even more frequent (and less efficient) TXG commits to stay within ARC size you can afford.

2021-05-14 17:18 UTC, jxdking commented
> Situations when the amount of dirty data is bigger than target ARC size are just insane, since you simply have no memory to handle so big transaction group and more frequent commit is the only way. Whether the 50%, 25% and 20% limits are perfect could be discussed, but in proper setup in my believe they should not be reached ever.

On second thought, it was bad idea to grow dirty data beyond arc_c. One question, is there any concern if allow dirty data to takes up to 100% acr_c or close to 100%? 
I plan just to expose zfs_arc_dirty_limit_percent to module parameters, so that we can tweak the percentage.

2021-05-15 12:32 UTC, amotin commented
> On second thought, it was bad idea to grow dirty data beyond arc_c. One question, is there any concern if allow dirty data to take up to 100% acr_c or close to 100%?

It means practically no other caching, evicting everything. It may work, but I doubt it can be efficient.

> I plan just to expose zfs_arc_dirty_limit_percent to module parameters, so that we can tweak the percentage.

This definitely should be done.  And for other variables there too.  Lack of tunables usually goes from Illumos, where global variables could be set directly via debugger.

2021-05-18 13:00 UTC, jxdking commented on module/zfs/arc.c
> -	    anon_size > rarc_c * zfs_arc_anon_limit_percent / 100 &&
It should be fine remove the check for anon_size, which is a part of total_dirty, right?

2023-03-28 00:42 UTC, closed without merging