Move EMPTY_TASKQ into taskq
openzfs/zfs pull request #12802
Opened 2021-11-27 02:48 UTC by lundman

A bit of code cleanup, moving taskq from icp into taskq.c

This assumes FreeBSD still does not use icp, but I have a feeling
they recently changed this?

### Motivation and Context

### Description

### How Has This Been Tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2021-11-27 06:33 UTC, rincebrain commented
> This assumes FreeBSD still does not use icp, but I have a feeling they recently changed this?

Well, the edonr code is being used, but the rest of the ICP is still not, AFAIK.

2021-11-30 19:04 UTC, behlendorf requested changes
I happened to notice that on illumos a new `taskq_empty()` function [was added](https://github.com/illumos/illumos-gate/commit/4c99ecc308d297ccc23eec0665e892052c57bf49).  Why don't we go ahead and adopt that interface instead for consistency.

2022-02-09 20:36 UTC, behlendorf approved these changes

2022-02-09 21:48 UTC, tonynguien approved these changes

2022-02-09 22:04 UTC, merged