FreeBSD: Fix leaked strings in libspl mnttab
openzfs/zfs pull request #12961
Opened 2022-01-11 17:54 UTC by freqlabs

### Motivation and Context

The FreeBSD implementations of various libspl functions for getting
mounted device informantion were found to leak several strings which
were being allocated in statfs2mnttab but never freed.

The Solaris getmntany(3C) and related interfaces are expected to return
strings residing in static buffers that need to be copied rather than
freed by the caller.

### Description

Use static thread-local storage to stash the mnttab structure strings
from FreeBSD's statfs info rather than strings allocated on the heap by
strdup(3).

While here, remove some stray commented out lines.

The definition of statfs2mnttab() was moved below init_statfs() for the convenience of using gsfs to help size the static buffer.

### How Has This Been Tested?

Ran full ZTS and passed on FreeBSD.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-01-11 21:55 UTC, rkojedzinszky commented
What if the cache is being used ? Wouldn't the local buffer be clobbered? Also, there are calls to free() those pointers in cache cleanup code.

2022-01-11 22:11 UTC, rkojedzinszky commented
> What if the cache is being used ? Wouldn't the local buffer be clobbered? Also, there are calls to free() those pointers in cache cleanup code. I mean the code path here: https://github.com/openzfs/zfs/blob/master/lib/libzfs/libzfs_dataset.c#L896
> 
> this will populate an internal cache, rewrting the local buffer, and also, upon exit, it will free() the entries in https://github.com/openzfs/zfs/blob/master/lib/libzfs/libzfs_dataset.c#L848

Sorry, it seems that I was too quick reading the code. During cache fill, the strings are strdup()-ed, so in the cache they are safe to use.

2022-01-12 11:47 UTC, rincebrain commented on lib/libspl/os/freebsd/mnttab.c
> +	char *p = buf, *e = buf + BUFSIZE;
Is there some reason I'm not seeing for preferring this mapping to just defining 4 separate __thread variables (or a struct with them, if you like) and referencing into that?

It seems unnecessary.

2022-01-12 18:01 UTC, amotin requested changes

2022-01-12 18:56 UTC, amotin approved these changes

2022-01-13 10:59 UTC, rincebrain approved these changes

2022-01-14 20:38 UTC, merged