Notice if the test-runner dies
openzfs/zfs pull request #12998
Opened 2022-01-22 14:24 UTC by nabijaczleweli

### Description
The Other Bit™ of #12990.

Decided to cannibalise `$REPORT_FILE` for the duration between finishing the test and starting the reporter instead of making another temp file.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes. – none apply
- [ ] I have run the ZFS Test Suite with this change applied. – CI will hopefully
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-01-22 15:16 UTC, szubersk commented on scripts/zfs-tests.sh
> -exit "${RESULT}"
A regular `if` statement would be much more readable.

2022-01-22 15:17 UTC, szubersk approved these changes

2022-01-22 15:17 UTC, szubersk commented on scripts/zfs-tests.sh
> +[ "$RUNRESULT" -ne 0 ] && exit "$RUNRESULT" || exit "$RESULT"
Regular `if` statement would be much more readable.

2022-01-22 16:52 UTC, rincebrain approved these changes
I was just going to wait a few days and hope people didn't bikeshed the next time, but this works.

2022-01-24 18:47 UTC, behlendorf requested changes
This change appears to result in all the TEST bots reporting failure.  The original intent was to only report failures if after retrying any failed tests we still have unexpected failures.

2022-01-27 22:29 UTC, nabijaczleweli commented
I rolled it back to only the first one (this is a direct translation of #12990 now), and it looks like they *both* globally fail all TEST buildds.

2022-01-27 22:33 UTC, rincebrain commented
[My original didn't, it seems.](http://build.zfsonlinux.org/builders/CentOS%207%20x86_64%20%28TEST%29/builds/18564) But the ones that use stashing $? do.

Curious.

2022-01-30 15:26 UTC, nabijaczleweli commented
I ran the tests in `set -x` mode, and the GHA test runners fail like the buildbot ones (previously this was just a spurious success), and forward non-zero results as expected, so I'm not quite sure what the intended result is, if not that (that being said, I know bugger-all about the tests, so it's not saying *much*)?

2022-01-30 15:57 UTC, rincebrain commented
I suspect, looking at it harder, that the current behavior is "error if we get a nonzero return from the test runner", when the case I actually wanted to notice was "just" "the test runner got killed/died unexpectedly, but it didn't log any test failures before doing so, so RESULT works out to be 0."

I don't actually know offhand what the exit code we'd see there is, versus what we're getting from the runner normally - I wasn't expecting the runner to be returning nonzero on successful run to completion, TBH, but you can see right there in summary() that it returns 1 if anything was KILLED or FAILed and 3 if it RERAN (and 2 if there were 0 tests). So presumably we want exit codes that are outside those.

2022-02-02 15:36 UTC, nabijaczleweli commented
Updated to `-gt 3` (so signaled, 128+x, and anything above RERAN) and the buildds fail as expected now I think?

2022-02-02 15:48 UTC, rincebrain commented
I already approved it, but I would agree that the failures seem correct. 👍

2022-02-02 16:19 UTC, nabijaczleweli commented
Rebased, squished :+1:

2022-02-02 22:14 UTC, behlendorf approved these changes

2022-02-02 22:17 UTC, merged