Cleanup: Correct memory barrier definitions
openzfs/zfs pull request #13843
Opened 2022-09-06 02:34 UTC by ryao

### Motivation and Context
When reading `module/zfs/zfs_ioctl.c`, I noticed a Linux kernel specific `smp_rmb()` in platform independent code that should have used `membar_consumer()`. This merits cleanup.

When cleaning it up, I noticed that FreeBSD had not defined `membar_consumer()`, but had defined `smp_rmb()` in `include/os/freebsd/linux/compiler.h` when `membar_producer()` had been in `include/os/freebsd/sys/atomic.h`. The definition for `membar_producer()` had been a full memory barrier, rather than the more performant store memory barrier that it was supposed to be.

### Description
I replaced `smp_rmb()` with `membar_consumer()`. I also deleted the  `smp_rmb()` definition from `include/os/freebsd/linux/compiler.h` and put the correct definitions in `include/os/freebsd/sys/atomic.h`.

### How Has This Been Tested?

It has not been tested. This kind of change should only require a build test. I intend to rely on the buildbot to verify that I have not broken kernel builds on either FreeBSD or Linux. I am not setup to compile FreeBSD here, so the buildbot's verification is a time saver for me.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-09-06 18:39 UTC, amotin requested changes
I like general cleanup, but I have feeling that FreeBSD part goes wrong way.  Comment in sys/amd64/include/atomic.h says:
```
/*
 * To express interprocessor (as opposed to processor and device) memory
 * ordering constraints, use the atomic_*() functions with acquire and release
 * semantics rather than the *mb() functions.  An architecture's memory
 * ordering (or memory consistency) model governs the order in which a
 * program's accesses to different locations may be performed by an
 * implementation of that architecture.  In general, for memory regions
 * defined as writeback cacheable, the memory ordering implemented by amd64
 * processors preserves the program ordering of a load followed by a load, a
 * load followed by a store, and a store followed by a store.  Only a store
 * followed by a load to a different memory location may be reordered.
 * Therefore, except for special cases, like non-temporal memory accesses or
 * memory regions defined as write combining, the memory ordering effects
 * provided by the sfence instruction in the wmb() function and the lfence
 * instruction in the rmb() function are redundant.  In contrast, the
 * atomic_*() functions with acquire and release semantics do not perform
 * redundant instructions for ordinary cases of interprocessor memory
 * ordering on any architecture.
 */
```

Since ZFS usually does not work with hardware directly, I think membar_producer() should be left as-is and membar_consumer() should be mapped to atomic_thread_fence_acq().  Those two on x86 do not create a full fence as you tell, but only with __compiler_membar() block memory access reorder by compiler, while hardware implements regular x86 memory model.  rmb()/wmd() on the other side generate explicit LFENCE/SFENCE instructions, that may be expensive and as written above redundant.

2022-09-06 22:43 UTC, ryao commented
@amotin `membar_producer()` and `membar_consumer()` are supposed to be sfence and lfence instructions respectively. That is how they are on OpenSolaris/Illumos:

https://github.com/illumos/illumos-gate/blob/master/usr/src/common/atomic/amd64/atomic.s#L564

On FreeBSD, `atomic_thread_fence_rel()` and `atomic_thread_fence_acq_rel()` are just `__compiler_membar()`:

https://github.com/freebsd/freebsd-src/blob/main/sys/amd64/include/atomic.h#L344

I had misinterpreted that to be a full barrier, but in fact, it is just prevents reordering by the compiler. `membar_producer()` and `membar_consumer()` are used in lockless code that absolutely must have a store/load barrier to work correctly. For example, the existing `smp_rmb()` that I wish to cleanup is in a lockless algorithm and switching to `__compiler_membar()` would introduce race conditions. I realize now that I mislabelled this cleanup as a performance enhancement because of the FreeBSD. I should have labelled it as a bug fix.

Do you still want to map these to functions that are basically `__compiler_membar()` on FreeBSD, even if Linux maps them to lfence and sfence like OpenSolaris does, and the code calling them expects them to be hardware fences?

2022-09-07 00:01 UTC, amotin commented
Unfortunately I can't say that I am a big expert in this area.  But I can say that atomic_thread_fence_acq/rel() on FreeBSD are mapped to __compiler_membar() only on x86 platforms.  For other platforms with less strict memory ordering they do explicitly call hardware synchronization.  On x86 AFAIK and as written in the quote above inter-CPU synchronization is a duty of hardware.  Exceptions are very rare, like devices access, rdtsc (which is not serializing, but often wanted so) and few others.  So from one side I don't want FreeBSD to be different, but from the other I'd like the code using these primitives in ZFS to be re-validated from the point whether the strict semantics is really required.

I'll call few other FreeBSD developers for help with this: @markjdb , @mjguzik , @kostikbel .

2022-09-07 00:10 UTC, amotin commented
As another argument to support my point, here are amd64 FreeBSD implementations of atomic_store_rel() and atomic_load_acq():
```
#define ATOMIC_LOAD(TYPE)                                       \
static __inline u_##TYPE                                        \
atomic_load_acq_##TYPE(volatile u_##TYPE *p)                    \
{                                                               \
        u_##TYPE res;                                           \
                                                                \
        res = *p;                                               \
        __compiler_membar();                                    \
        return (res);                                           \
}                                                               \
struct __hack

#define ATOMIC_STORE(TYPE)                                      \
static __inline void                                            \
atomic_store_rel_##TYPE(volatile u_##TYPE *p, u_##TYPE v)       \
{                                                               \
                                                                \
        __compiler_membar();                                    \
        *p = v;                                                 \
}                                                               \
struct __hack
```
As you may see, they have only compiler barriers, and those are sufficient for the kernel primitives.  All other synchronization on x86 is done my hardware.

2022-09-07 03:09 UTC, ryao commented
> As another argument to support my point, here are amd64 FreeBSD implementations of atomic_store_rel() and atomic_load_acq():
> 
> ```
> #define ATOMIC_LOAD(TYPE)                                       \
> static __inline u_##TYPE                                        \
> atomic_load_acq_##TYPE(volatile u_##TYPE *p)                    \
> {                                                               \
>         u_##TYPE res;                                           \
>                                                                 \
>         res = *p;                                               \
>         __compiler_membar();                                    \
>         return (res);                                           \
> }                                                               \
> struct __hack
> 
> #define ATOMIC_STORE(TYPE)                                      \
> static __inline void                                            \
> atomic_store_rel_##TYPE(volatile u_##TYPE *p, u_##TYPE v)       \
> {                                                               \
>                                                                 \
>         __compiler_membar();                                    \
>         *p = v;                                                 \
> }                                                               \
> struct __hack
> ```
> 
> As you may see, they have only compiler barriers

The existing FreeBSD SPL uses `atomic_thread_fence_rel()`, which is not implemented by either of these.

> and those are sufficient for the kernel primitives. All other synchronization on x86 is done by hardware.

How? I do not see any synchronization being done by hardware in things that use membar_producer()/membar_consumer() without the memory fences.

For example, let us take a look at `zfsdev_state_init()`. It implements linked list that may be read without taking a lock to fix this deadlock:

https://github.com/openzfs/zfs/issues/2301

The way that it works is fairly simple:

* Modification is only ever done under a lock.
* Entries in the list are never actually freed.
* Entries may be marked unused by setting the minor to -1.
* New entries are added at the tail of the list.

It uses a store fence when either adding a new entry or marking an existing entry as in use. Let us say that we are marking an entry as in use without the store fence on processor A. That means a superscalar architecture is free to reorder `zs->zs_minor = minor;` before `zfs_zevent_init((zfs_zevent_t **)&zs->zs_zevent);` sets `zs->zs_zevent`. Then processor B executes `zfsdev_get_state(minor, ZST_ZEVENT)`, which reads the list. Since `zs->zs_minor == minor` matches, it then returns `zs->zs_zevent`, which is a bad value because the correct value is still in the store buffer of processor A (as per the MOESI protocol).

If we were excecuting on a SMP version of the 486, then a compiler memory barrier would be fine, since the stores would be done in-order, but modern CPUs are superscalar that are free to re-order stores, so compiler memory barriers are not very useful for synchronization. Sometimes, the hardware might not reorder and we would be fine, but then a new processor can be made that exploits the re-ordering opportunity and then we have a very rare and very hard to debug race condition. This is just one example. Every case in the code that uses either membar_producer() or membar_consumer() should expect a memory fence, as they would have been used specifically to do a memory fence.

Despite what some documentation might say, memory fences are cheap. They are cheaper than any other synchronization primitive when you need synchronization. They are only expensive relative to not having any synchronization at all, but you cannot have concurrent access to data structures without some kind of synchronization. As I said previously, a compiler memory barrier is not synchronization on a superscalar processor. Concurrent access to data without synchronization is a race condition.

Lastly, we might by clever and observe that releasing the zfsdev_state_lock mutex would flush the store buffer. While that is true, there is still an opportunity for another processor to see memory in an invalid state before that is done. Furthermore, a CPU interrupt occurring right before the mutex release does a store buffer flush could delay the store buffer flush for an indefinite period of time, making the race much bigger than the few cycles that it would seem to be. That said, even races that are a few cycles long can cause problems. :/

2022-09-07 03:39 UTC, amotin commented
@ryao I do understand the concept of barriers in general, but x86 in particular is more forgiving than other architectures.  You may look on "Memory ordering in some architectures" table at https://en.wikipedia.org/wiki/Memory_ordering.  Or if you wish more serious document on "8.2.2 Memory Ordering in P6 and More Recent Processor Families" chapter at [Intel® 64 and IA-32 Architectures Software Developer's Manual Volume 3A: System Programming Guide, Part 1](https://cdrdv2.intel.com/v1/dl/getContent/671190):

In a single-processor system for memory regions defined as write-back cacheable, the memory-ordering model respects the following principles:
• Reads are not reordered with other reads.
• Writes are not reordered with older reads.
• Writes to memory are not reordered with other writes, with the following exceptions ...
...
In a multiple-processor system, the following ordering principles apply:
• Individual processors use the same ordering principles as in a single-processor system.
• Writes by a single processor are observed in the same order by all processors.
...
The processor-ordering model described in this section is virtually identical to that used by the Pentium and Intel486 processors. The only enhancements in the Pentium 4, Intel Xeon, and P6 family processors are:
• Added support for speculative reads, while still adhering to the ordering principles above.
• Store-buffer forwarding, when a read passes a write to the same memory location.
• Out of order store from long string store and string move operations ...

2022-09-07 03:45 UTC, ryao commented
> @ryao I do understand the concept of barriers in general, but x86 in particular is more forgiving than other architectures. You may look on "Memory ordering in some architectures" table at https://en.wikipedia.org/wiki/Memory_ordering. Or if you wish more serious document on "8.2.2 Memory Ordering in P6 and More Recent Processor Families" chapter at [Intel® 64 and IA-32 Architectures Software Developer's Manual Volume 3A: System Programming Guide, Part 1](https://cdrdv2.intel.com/v1/dl/getContent/671190):
> 
> In a single-processor system for memory regions defined as write-back cacheable, the memory-ordering model respects the following principles: • Reads are not reordered with other reads. • Writes are not reordered with older reads. • Writes to memory are not reordered with other writes, with the following exceptions ... ... In a multiple-processor system, the following ordering principles apply: • Individual processors use the same ordering principles as in a single-processor system. • Writes by a single processor are observed in the same order by all processors. ... The processor-ordering model described in this section is virtually identical to that used by the Pentium and Intel486 processors. The only enhancements in the Pentium 4, Intel Xeon, and P6 family processors are: • Added support for speculative reads, while still adhering to the ordering principles above. • Store-buffer forwarding, when a read passes a write to the same memory location. • Out of order store from long string store and string move operations ...

@amotin Honestly, I posted that before I should have and ended up editing it up until you replied. Anyway, I think I understand the problem here. You assume that we only support architectures that do total store ordering. We support both ARM and POWER, which do not implement total store ordering:

https://en.wikipedia.org/wiki/Memory_ordering#In_symmetric_multiprocessing_(SMP)_microprocessor_systems

I understand that FreeBSD also supports ARM and PPC:

https://www.freebsd.org/platforms/arm/
https://www.freebsd.org/platforms/ppc/

That said, I now understand your aversion to using these instructions on x86/amd64. It does look like they are unnecessary, provided that we use compiler memory barriers. I am open to switching to compiler memory barriers on x86/amd64, but we still need the fences on other architectures.

Would that be satisfactory?

2022-09-07 03:54 UTC, amotin commented
> That said, I now understand your aversion to using these instructions on x86/amd64. It does look like they are unnecessary, provided that we use compiler memory barriers. I am open to switching to compiler memory barriers on x86/amd64, but we still need the fences on other architectures.
> 
> Would that be satisfactory?

As I have told above: "But I can say that atomic_thread_fence_acq/rel() on FreeBSD are mapped to __compiler_membar() only on x86 platforms. For other platforms with less strict memory ordering they do explicitly call hardware synchronization."  It would be good to find closest atomic_thread_fence_acq/rel() counterparts on other architectures.  Otherwise FreeBSD may indeed appear different.  Unless I am completely wrong and somebody correct me. ;)

2022-09-07 04:11 UTC, ryao commented
@amotin It has been years since I last thought about this and honestly, I never thought about exploiting x86/amd64's TSO to avoid these. The practice in both OpenSolaris and Linux is to use explicit fences and I never had a reason to question it until now. After thinking about it, you were right from the start. I just pushed a new patch that uses `atomic_thread_fence_acq/rel()` on FreeBSD and adopts that behavior on Linux.

Thank you for your feedback and for taking the time to explain things to me after I failed to understand them at first. :)

2022-09-07 04:25 UTC, ryao commented
After scrutinizing the Linux kernel sources more closely, it turns out that Linux also implements the optimization where it replaces lfence/sfence with a compiler memory barrier in `smp_rmb()` and `smp_wmb()`. OpenSolaris/Illumos are alone in inserting lfence/sfence on x86/amd64. I just simplified my patch based on that.

2022-09-07 09:23 UTC, kostikbel commented on module/zfs/zfs_ioctl.c
> +			membar_consumer();
I assume there is a dual membar_producer() already existing in the code at the right place?

2022-09-07 10:01 UTC, mjguzik commented
As @amotin said these are the correct barriers, so the patch is fine in terms of what it modifies.

However, I could not help but note there is no full barrier implemented in the list which I find highly suspicious.

On Linux it would be smp_mb, on FreeBSD atomic_thread_fence_seq_cst. These happen to not just compile out even on amd64.

Grep reveals membar_enter and membar_exit, which are quite frankly weird -- both provide a full barrier and are not used anywhere.

Instead there is a wrong redefinition of  in module/icp/include/sys/crypto/impl.h:
```
/* atomic operations in linux implicitly form a memory barrier */
#define membar_exit()
```

Should the above be needed, on Linux you would  smp_mb__before/after_atomic. Unfortunately FreeBSD does not provide an equivalent right now.

Sample usage:
```
#define KCF_PROV_IREFRELE(desc) {                               \
        ASSERT((desc)->pd_irefcnt != 0);                        \
        membar_exit();                                          \
        if (atomic_add_32_nv(&(desc)->pd_irefcnt, -1) == 0) {   \
                cv_broadcast(&(desc)->pd_remove_cv);            \
        }                                                       \
}
```

This most likely only needs a release fence, not a full barrier -- as in membar_producer, although it does look weird given the naming.

That said, the patch as is provides an improvement and perhaps can go in, but there is more work to do in the area.

2022-09-07 12:11 UTC, freqlabs commented on module/zfs/zfs_ioctl.c
> +			membar_consumer();
In `zfsdev_state_init()`: https://github.com/openzfs/zfs/blob/825ab2ae07ac2d9e562e61af1ead1e0b85219948/module/zfs/zfs_ioctl.c#L7553-L7568
and `zfsdev_state_destroy()`: https://github.com/openzfs/zfs/blob/825ab2ae07ac2d9e562e61af1ead1e0b85219948/module/zfs/zfs_ioctl.c#L7581-L7594

2022-09-07 13:42 UTC, amotin approved these changes

2022-09-07 14:01 UTC, mjguzik commented on module/zfs/zfs_ioctl.c
> +			membar_consumer();
I don't think this code is correct. First a small note that it should be using atomic_store or an equivalent to make sure the kernel does not split writes (normally it does not happen so it's not a big deal for the most part).

Another small note is that this probably should not be a linked list to begin with.

`
        for (zs = zfsdev_state_list; zs != NULL; zs = zs->zs_next) {
                if (zs->zs_minor == minor) {
                        smp_rmb();
`

Code ensures to load zs_minor first (and elsewhere to store it last). But by the time any of the following code executes, the entry at hand could have been freed and/or reused with minor changed. Consequently...

`
                       switch (which) {
                        case ZST_ONEXIT:
                                return (zs->zs_onexit);
`

... this and other loads could be accessing zs with a different minor, but nothing checks it is still the correct one. Let's say the code got augmented and now ends with:

`
smp_rmb();
if (zs->zs_minor == minor)
    /* got em */
   ....
else
   /* fail */
   ....
`

Even then particular zs entry could have been freed and/or reused and the consumer is once more accessing stale/wrong data.

The thing to add here is reference counting which will bump-if-not-zero to prevent races against reuse.

2022-09-07 14:39 UTC, freqlabs commented on module/zfs/zfs_ioctl.c
> +			membar_consumer();
My understanding is that the state is protected from use after free because `zfsdev_state_destroy()` is only called on the last filedescriptor close (arranged on FreeBSD by `devfs_set_cdevpriv()`), so nothing else could be looking up this minor by the time we're destroying it.

2022-09-07 14:49 UTC, mjguzik commented on module/zfs/zfs_ioctl.c
> +			membar_consumer();
The worry is not about proper handling of alloc vs free, but whoever is doing lockless lookup here. I'm going to ponder around some more, this is all very suspicious.

2022-09-07 15:53 UTC, mjguzik commented on module/zfs/zfs_ioctl.c
> +			membar_consumer();
So I looked some more, the commit which introduced the thing claimed problems in txg_sync. "just" using zfs makes me unable to land in the lookup routine, so I'm wondering if the original justification holds to begin with. Perhaps this can be safely reverted to prior state?

2022-09-07 16:17 UTC, ryao commented on module/zfs/zfs_ioctl.c
> +			membar_consumer();
The original deadlock that this was intended to fix is described here:

https://github.com/openzfs/zfs/issues/2301#issuecomment-42362773

Reverting it would require that we be certain that this deadlock cannot happen. I will need to scrutinize this more later to form an opinion on whether the problem is still there.

2022-09-07 16:20 UTC, ryao commented
@mjguzik The identical membar_enter and membar_exit weirdness is explained in the Illumos/OpenSolaris source code:

https://github.com/illumos/illumos-gate/blob/master/usr/src/common/atomic/amd64/atomic.s#L547

In short, it was for DTrace.

2022-09-08 11:28 UTC, freqlabs commented on module/zfs/zfs_ioctl.c
> +			membar_consumer();
Put another way, I don't think the state will be destroyed/reused until any lookups what would ever occur for that state have completed. Doing a lookup means you have an open fd the state is or will be associated with. Can ioctl race with close?

2022-09-08 20:32 UTC, behlendorf approved these changes

2022-09-11 22:21 UTC, Conan-Kudo approved these changes

2022-09-12 19:43 UTC, ryao commented
> /* atomic operations in linux implicitly form a memory barrier */
> #define membar_exit()

This is definitely wrong. Atomics only form memory barriers on architectures that do not reorder atomics (and a quick look at the Linux kernel source code confirmed the lack of barriers on IA64). Most architectures will reorder atomics:

https://en.wikipedia.org/wiki/Memory_ordering#In_symmetric_multiprocessing_(SMP)_microprocessor_systems

That said, the original code did not use atomics, but instead used a mutex:

https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/sys/crypto/impl.h#L252

I will tackle this in a separate patch, since I will not be implementing `membar_exit()`, but eliminating the need for it entirely.

2022-09-12 20:07 UTC, ryao commented
@mjguzik I have just opened #13880 with fixes for `module/icp/include/sys/crypto/impl.h`.

2022-09-13 23:59 UTC, merged