Cleanup: Use OpenSolaris functions to call scheduler
openzfs/zfs pull request #13845
Opened 2022-09-06 02:48 UTC by ryao

### Motivation and Context
In our codebase, `cond_resched()` and `schedule()` are Linux kernel
functions that have replaced the OpenSolaris `kpreempt()` and `swtch()`
functions in the codebase to such an extent that `kpreempt()` in
zfs_context.h was broken and `swtch()` was unimplemented. Nobody noticed
because we did not actually use either of them. The header had defined
`kpreempt()` as `yield()`, which works on OpenSolaris and Illumos where
`sched_yield()` is a wrapper for `yield()`, but that does not work on any
other platform.

The FreeBSD platform specific code implemented shims for these, but the
shim for `schedule()` forced us to wait, which is different than merely
rescheduling to another thread as the original Linux code does, while
the shim for `cond_resched()` had the same definition as its kernel
`kpreempt()` shim.

The use of Linux functions in what should be OpenSolaris code and the
incorrect implementation of one of those functions in FreeBSD's SPL is
needlessly confusing and merits cleanup. This should have the benefit
of making it slightly easier to port the code to new platforms by making
how things should be mapped less confusing.

### Description
This patch reintroduces the `swtch()` and `kpreempt()` functions in platform
independent code with the following definitions:

	- In the Linux kernel:
		swtch()			-> schedule()
		kpreempt(unused)	-> cond_resched()

	- In the FreeBSD kernel:
		swtch()			-> kern_yield(PRI_UNCHANGED)
		kpreempt(unused)	-> kern_yield(PRI_USER)

	- In userspace:
		swtch()			-> sched_yield()
		kpreempt(unused)	-> sched_yield()

Both in the Linux kernel and in userspace, nothing changes from this
cleanup. In the FreeBSD kernel, the function `fm_fini()` will call
`kern_swtch(PRI_UNCHANGED)` instead of `pause("schedule", 1)`, which
makes its behavior analogous to the Linux behavior. The `fm_fini()`
function appears to have originally been written against Linux, so
mimicking the Linux behavior should be correct.

Note that Linux's SPL continues to use `cond_resched()` and `schedule()`.
However, those functions have been removed from both the FreeBSD code
and userspace code.

### How Has This Been Tested?

No testing has been done. On Linux, the compiled binary is expected to be the same, so only compile testing by the buildbot is considered necessary. On FreeBSD, only a single call into the scheduler changes to a definition that is more appropriate. Compile testing should also be sufficient there.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-09-06 21:39 UTC, amotin requested changes
Rescheduling in a tight loop without dropping priority (swtch() inside fm_fini()) makes my eyes bleed.  I have feeling that it may work only if other threads the code is waiting for is running at exactly the same priority, that I don't even wish to check.  And even then it is a CPU burning, even though rare and probably small.  I would prefer swtch() KPI to be dropped as bad code practice and the fm_fini() to be rewritten with normal waiting.

PS: But thanks for cleaning this up. I am really grateful.

PPS: Or at very least why not use kpreempt() inside fm_fini() just to unify the KPI?  Why should it be different?

2022-09-06 22:23 UTC, ryao commented
@amotin That is a good question. @behlendorf wrote this back when the repository only supported Linux. I have no idea why he chose to use the schedule() function over cond_resched(). There are plenty of other places in the Linux SPL where we do this, so I decided not to question it when I wrote this change. I would be happy to switch this call to kpreempt() and drop swtch().

@behlendorf Is there any special reason that you did not make this use cond_resched() when you wrote it?

2022-09-08 20:49 UTC, behlendorf approved these changes
Thanks for cleaning this up!  As for `fm_fini()` I don't see any reason we can't use `cond_resched()` there.

2022-09-09 19:45 UTC, ryao commented
I have just pushed a new version that eliminates `swtch()` in favor of `kpreempt()`. It should address everything that has been discussed.

2022-09-09 19:55 UTC, amotin approved these changes

2022-09-11 22:22 UTC, Conan-Kudo approved these changes

2022-09-12 16:55 UTC, merged