Add membar_sync
openzfs/zfs pull request #13907
Opened 2022-09-17 00:51 UTC by mjguzik

Provides the missing full barrier variant to the membar primitive set.

While not used right now, this is probably going to change down the road.

Name taken from Solaris, to follow the existing routines.

### Motivation and Context

### Description

### How Has This Been Tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-09-17 01:27 UTC, ryao requested changes
This should be added to lib/libspl/include/atomic.h and lib/libspl/atomic.c too.

2022-09-17 12:29 UTC, mjguzik commented
How is lib/libuutil/libuutil.abi managed? Looks like I'll need to plop it in there.

2022-09-17 16:07 UTC, ryao commented
> How is lib/libuutil/libuutil.abi managed? Looks like I'll need to plop it in there.

The commit history for that file suggests that it is generated by a tool in libabigail.

2022-09-17 17:53 UTC, gmelikov commented
@mjguzik just push changed code, and our "checkstyle" CI runner will generate new abi files which will be available to download and push in case if abi changed.

2022-09-17 23:51 UTC, ryao approved these changes
This looks good to me.

checkabi is also happy since this symbol is not in the list of symbols that it is watching. :)

2022-09-20 22:31 UTC, behlendorf approved these changes

2022-09-20 22:32 UTC, merged