Fix minor issues in namespace delegation support
openzfs/zfs pull request #13918
Opened 2022-09-18 11:51 UTC by youzhongyang

Signed-off-by: Youzhong Yang <yyang@mathworks.com>

This PR fixes a logic error in spl_zone_fini(), and two test cases.

### Motivation and Context

While reviewing the Linux namespace delegation support, I noticed these minor issues which are easy to fix, so here it is.

### Description

- get_user_ns() is only done once for each namespace, so put_user_ns() should be done once too.
- The two typos in user_namespace/user_namespace_002.ksh and user_namespace/user_namespace_003.ksh.

### How Has This Been Tested?

Built and ran user_namespace test cases.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-09-19 07:22 UTC, ryao approved these changes

2022-09-20 00:19 UTC, behlendorf approved these changes

2022-09-20 20:00 UTC, freqlabs requested changes
`get_user_ns()` is called for every dataset, not every namespace. This was correct the way it was.

2022-09-20 20:03 UTC, freqlabs approved these changes
Sorry you're right, it's called in `zone_dataset_attach()` only for the first dataset.

2022-09-20 20:07 UTC, ryao approved these changes

2022-09-20 22:25 UTC, merged