btree_test: smatch did detect few issues
openzfs/zfs pull request #13941
Opened 2022-09-23 12:38 UTC by tsoome

Add missing header.
Properly ignore return values.

Memory leak/unchecked malloc. We do allocate a bit too early (and fail to validate the result). From this, smatch is angry when we overwrite the value of 'node' later.

Signed-off-by: Toomas Soome <tsoome@me.com>

### Motivation and Context

### Description

### How Has This Been Tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-09-23 16:45 UTC, ikozhukhov approved these changes

2022-09-23 17:32 UTC, ryao requested changes
The leak also was caught by coverity and has a fix in #13921. I did not handle the potential for malloc() to return NULL since I assumed at that point, the test result was invalid and hitting a NULL pointer dereference would be enough. This version should report a test failure, but it will not be obvious that it is from malloc() failing.

I suggest printing a warning and just terminating so that we do not send anyone on a search for a bug that does not exist if malloc() fails.

2022-09-23 20:53 UTC, tsoome commented
> The leak also was caught by coverity and has a fix in #13921. I did not handle the potential for malloc() to return NULL since I assumed at that point, the test result was invalid and hitting a NULL pointer dereference would be enough. This version should report a test failure, but it will not be obvious that it is from malloc() failing.
> 
> I suggest printing a warning and just terminating so that we do not send anyone on a search for a bug that does not exist if malloc() fails.

I actually figured to use ASSERT3P - should follow the logic used in this code.

2022-09-23 20:54 UTC, ryao commented
> I actually figured to use ASSERT3P - should follow the logic used in this code.

I am fine with either approach. :)

2022-09-23 21:04 UTC, ryao approved these changes

2022-09-24 00:00 UTC, ryao commented
@tsoome This needs to be rebased against master, since #13921 was merged, which causes a merge conflict.

2022-09-28 00:07 UTC, behlendorf approved these changes

2022-09-28 00:09 UTC, merged