Avaid unnecessary metaslab_check_free calling
openzfs/zfs pull request #13977
Opened 2022-10-01 15:16 UTC by Finix1979

Because zio_free_sync has called metaslab_check_free, zio_free could check it only for GANG|dedup etc.

Signed-off-by: Finix1979 <yancw@info2soft.com>

### Motivation and Context

### Description

### How Has This Been Tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-10-01 17:35 UTC, ryao requested changes
There is a typo in the commit name. Please change "Avaid" to "Avoid" and repush.

Other than that, this looks good to me. I will approve it after the typo correction is done.

2022-10-02 13:43 UTC, Finix1979 commented
> There is a typo in the commit name. Please change "Avaid" to "Avoid" and repush.
> 
> Other than that, this looks good to me. I will approve it after the typo correction is done.

@ryao  It's done. Thank you.

2022-10-02 14:51 UTC, ryao approved these changes

2022-10-04 17:42 UTC, behlendorf approved these changes

2022-10-04 17:55 UTC, merged