isa_defs.h cleanups (RISC-V and GC)
openzfs/zfs pull request #14128
Opened 2022-11-02 16:21 UTC by brooksdavis

### Motivation and Context
I needed to improve the RISC-V entry in the common isa_defs.h for CheriBSD. This PR contains that and some follow on changes.

### Description
Based on feedback from @ryao I've added the RISC-V changes to the linux SPL. I've also included a follow on cleanup to the Linux isa_defs.h following FreeBSD changes in #14127.

### How Has This Been Tested?
zfs-test sanity tests on FreeBSD.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

Requires-builders: build

2022-11-02 16:37 UTC, ryao requested changes
This looks good to me, but there are a couple checkstyle complaints that need to be addressed before these commits can be merged.

2022-11-02 16:37 UTC, ryao commented on include/os/linux/spl/sys/isa_defs.h
> +#endif
Our coding style requires a tab follow `#define` rather than a space.

2022-11-02 16:37 UTC, ryao commented on lib/libspl/include/sys/isa_defs.h
> +#endif
Same here.

2022-11-02 16:45 UTC, brooksdavis commented on include/os/linux/spl/sys/isa_defs.h
> +#endif
Fixed

2022-11-02 16:48 UTC, ryao approved these changes

2022-11-03 16:38 UTC, behlendorf approved these changes

2022-11-03 16:40 UTC, closed without merging