Python3: replace `distutils` with `sysconfig`
openzfs/zfs pull request #14177
Opened 2022-11-13 06:37 UTC by szubersk

### Motivation and Context
Fix #12833
Fix #13280

### Description
`distutils` module is long time deprecated and already deleted from the CPython mainline.

### How Has This Been Tested?
./configure --enable-pyzfs

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-11-14 13:44 UTC, ryao approved these changes

2022-11-14 15:01 UTC, behlendorf approved these changes

2022-11-15 07:17 UTC, rincebrain commented
I should point out that on Debian, this now puts pyzfs in `/usr/lib/python3.9/site-packages/`, when the old packaging put it in `/usr/lib/python3/dist-packages/`, since [Debian patches distutils but not sysconfig to put their preferred paths in](https://ffy00.github.io/blog/02-python-debian-and-the-install-locations/).

2022-11-15 20:50 UTC, behlendorf commented
Does this result in a problem, or is it just something we should give the Debian packagers a heads up on?

2022-11-15 21:01 UTC, rincebrain commented
I would imagine that if you have more than one Python3 installed, this could break you, but that's not a default config.

I would ask someone more familiar with Debian's Python packaging, tbh, as I don't use pyzfs, I just knew that this changed where things got put, and couldn't find a solution to put them where they were other than hardcoding the old result.

2022-11-15 21:27 UTC, ryao commented
@rincebrain Nice catch.

@behlendorf `dist-packages` is a Debian invention:

https://wiki.debian.org/Python#Deviations_from_upstream

The write-up that @rincebrain quoted gives a better description of the state of things:

https://ffy00.github.io/blog/02-python-debian-and-the-install-locations/

In summary, this should affect all Debian-based distributions, including Ubuntu, and there is no recommended way to prepare for upstream python's plan to remove it from python 3.12 since it is not known what Debian will do in python 3.12.

We would definitely want to give the Debian and Ubuntu maintainers a heads up about this if we merge it as is. However, it would be less painful for users of distributions in the Debian family that wish to build things themselves if we continued to support their non-standard installation locations.

2022-11-15 21:29 UTC, behlendorf commented
@cdluminate would you mind commenting on this proposed change from a Debian perspective.

2022-11-15 21:30 UTC, ryao requested changes
After thinking about this, I think the best way forward to be as backward compatible with Debian and Debian derived distributions as possible would be to do the following:

* Make an autotools check that runs a python script to check if `distutils.sysconfig.get_python_inc()` works and is not equal to `sysconfig.get_path('include')`. If both are the case, we use `distutils.sysconfig.get_python_inc()`. Otherwise, we use  `sysconfig.get_path('include')`.
* Change rpm/generic/zfs.spec.in to use `@PYTHON_GET_LIB@` and then set that to either `"from distutils.sysconfig import get_python_lib; print(get_python_lib())"` or `"import sysconfig; print(sysconfig.get_path('purelib'))"` in autotools based on the aforementioned check.

I would have said to just use sysconfig unconditionally in `rpm/generic/zfs.spec.in`, but unfortunately, we can use alien to generate packages based on the RPM packages for other systems, so it is possible that we would be doing the wrong thing for a distribution without that autotools check.

2022-11-15 21:37 UTC, ryao commented
I had assumed that the ZTS passing on the buildbot implied that this was fine on Debian systems, but upon closer inspection, it turns out that build bot will assume a failure in `pyzfs_unittest` is due to a missing python3-cffi, so it will mark the test as SKIP rather than FAIL:

`SKIP pyzfs/pyzfs_unittest (Python modules missing: python3-cffi)`

That is how it got past my review in the first place, since I decided to trust the buildbot results without scrutinizing one level deeper. :/

2022-11-16 00:24 UTC, cdluminate commented
Debian has only one default python3 version. I don't expect any major issues here. While something might go wrong during the python3 transition (breaks lots of packages), a temporary hard-coded path fix is convenient for Debian packaging.

That said, the old path is better for Debian, as the resulting `python3-pyzfs` package will not depend on a specific python version. Afterall the cffi code should be invariant to python3 version. So it would be better if there is sensible ways as suggested above to use the old path.

BTW,  where can I find the buildlog for the `SKIP pyzfs/pyzfs_unittest (Python modules missing: python3-cffi)` failure?

2022-11-16 00:43 UTC, ryao commented
> BTW, where can I find the buildlog for the `SKIP pyzfs/pyzfs_unittest (Python modules missing: python3-cffi)` failure?

https://github.com/openzfs/zfs/actions/runs/3454892920/jobs/5766528329

There should be a corresponding artifacts file, but I am having trouble finding it.

2022-11-16 01:46 UTC, rincebrain commented
Currently the CI only saves artifacts if it thinks it failed.

2022-11-16 03:46 UTC, szubersk commented
Looks like it's an internal Debian issue that has been corrected over time and propagated to Ubuntu as well. I'd say we stick to the standard `sysutils` usage and leave adjustments to the folks down the stream.
The most recent default value is `/usr/local/lib/python3.10/dist-packages` which looks reasonable: non-standard site modules go by default to `/usr/local/lib` and they do not interfere with modules installed via `dpkg` to `/usr/lib`. I'd presume that was the Debian developers' intention.

I'll investigate the CI issue later on.

```
debian:buster
be82c627fbdbfafd819f961a52a53366988ff0829c06d27f744cd7f90acc6fa1
old  /usr/include/python3.7m                  /usr/include/python3.7m                 
new  /usr/include/python3.7m                  /usr/include/python3.7m                 

old  /usr/lib/python3/dist-packages           /usr/lib/python3/dist-packages           /usr/lib/python3.7                       /usr/lib/python3.7                      
new  /usr/lib/python3.7/site-packages         /usr/lib/python3.7/site-packages         /usr/lib/python3.7                       /usr/lib/python3.7

debian:bullseye
ef39063a944dfcf2f1649509b358b2763d129c5931c99b429c59f645d20ae5dd
old  /usr/include/python3.9                   /usr/include/python3.9                  
new  /usr/include/python3.9                   /usr/include/python3.9                  

old  /usr/lib/python3/dist-packages           /usr/lib/python3/dist-packages           /usr/lib/python3.9                       /usr/lib/python3.9                      
new  /usr/lib/python3.9/site-packages         /usr/lib/python3.9/site-packages         /usr/lib/python3.9                       /usr/lib/python3.9

debian:bookworm
c13e86861a1e3590f6b357eadb2bef6413e32eed5f64f40194c37df0dbdf6e0a
old  /usr/include/python3.10                  /usr/include/python3.10                 
new  /usr/include/python3.10                  /usr/include/python3.10                 

old  /usr/lib/python3/dist-packages           /usr/lib/python3/dist-packages           /usr/lib/python3.10                      /usr/lib/python3.10                     
new  /usr/local/lib/python3.10/dist-packages  /usr/local/lib/python3.10/dist-packages  /usr/lib/python3.10                      /usr/lib/python3.10

debian:sid
ff3f25ad432915c0a9e145db5413df491e9575fdeedaac8479121695c91b5eec
old  /usr/include/python3.10                  /usr/include/python3.10                 
new  /usr/include/python3.10                  /usr/include/python3.10                 

old  /usr/lib/python3/dist-packages           /usr/lib/python3/dist-packages           /usr/lib/python3.10                      /usr/lib/python3.10                     
new  /usr/local/lib/python3.10/dist-packages  /usr/local/lib/python3.10/dist-packages  /usr/lib/python3.10                      /usr/lib/python3.10

ubuntu:jammy
3c2df5585507842f5cab185f8ad3e26dc1d8c4f6d09e30117af844dfa953f676
old  /usr/include/python3.10                  /usr/include/python3.10                 
new  /usr/include/python3.10                  /usr/include/python3.10                 

old  /usr/lib/python3/dist-packages           /usr/lib/python3/dist-packages           /usr/lib/python3.10                      /usr/lib/python3.10                     
new  /usr/local/lib/python3.10/dist-packages  /usr/local/lib/python3.10/dist-packages  /usr/lib/python3.10                      /usr/lib/python3.10

ubuntu:kinetic
bd0f2ee1f44f455fd39461966b77ea59a9ea596ea71359c52ab7e91571afac2e
old  /usr/include/python3.10                  /usr/include/python3.10                 
new  /usr/include/python3.10                  /usr/include/python3.10                 

old  /usr/lib/python3/dist-packages           /usr/lib/python3/dist-packages           /usr/lib/python3.10                      /usr/lib/python3.10                     
new  /usr/local/lib/python3.10/dist-packages  /usr/local/lib/python3.10/dist-packages  /usr/lib/python3.10                      /usr/lib/python3.10
```

Methodology
```
(while read -r d r; do echo $d:$r; podman pull -q $d:$r; podman run --rm -i $d:$r bash - < python-check; echo; done) < distros
```

python-check
```
set -e
{ apt-get -qq update; apt-get -qq install python3-distutils; } > /dev/null 2>&1
python3 -c "
from distutils import sysconfig as ds
import sysconfig as s
print(f\"{'old':<4} {ds.get_python_inc(0) : <40} {ds.get_python_inc(1) : <40}\")
print(f\"{'new':<4} {s.get_path('include') : <40} {s.get_path('platinclude') : <40}\")
print()
print(f\"{'old':<4} {ds.get_python_lib(0,0) : <40} {ds.get_python_lib(1,0) : <40} {ds.get_python_lib(0,1) : <40} {ds.get_python_lib(1,1) : <40}\")
print(f\"{'new':<4} {s.get_path('purelib') : <40} {s.get_path('platlib') : <40} {s.get_path('stdlib') : <40} {s.get_path('platstdlib')}\")
" 2>/dev/null
```

2022-11-27 09:04 UTC, szubersk commented
Feels like the problem's solved. Feel free to review.

2022-11-28 19:39 UTC, merged