zed: unclean disk attachment faults the vdev
openzfs/zfs pull request #14181
Opened 2022-11-15 02:09 UTC by ixhamza

### Description

If the attached disk already contains a vdev GUID, it means the disk is not clean. In such a scenario, the physical path would be a match that makes the disk faulted when trying to online it. So, we would only want to proceed if either GUID matches with the last attached disk or the disk is in clean state.

### How Has This Been Tested?

Through qemu emulated drives

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-11-15 12:31 UTC, ixhamza commented
@amotin, @freqlabs, @tonyhutter.

2022-11-22 15:15 UTC, amotin requested changes

2022-11-22 15:15 UTC, amotin commented on cmd/zed/agents/zfs_mod.c
> +	(void) nvlist_lookup_uint64(nvl, ZPOOL_CONFIG_GUID, &guid);
It looks like guid may end up uninitialized here. Unlikely, but still. Either check for error here or set it to zero above.

2022-11-22 15:15 UTC, amotin commented on cmd/zed/agents/zfs_mod.c
> +			}
The code would be much more readable if you split this block into two, one checking paths as-is, and add another separate matching the guids.  Then you would not need second dp->dd_new_vdev_guid != 0 check (that is actually incorrect if we got here due to path mismatch).

2022-11-28 16:50 UTC, freqlabs approved these changes

2022-11-28 17:13 UTC, amotin approved these changes

2022-11-28 17:13 UTC, amotin commented on cmd/zed/agents/zfs_mod.c
> +		    != guid) {
You don't need "else" here because of "return".  As result it would fit one line.

2022-11-28 19:49 UTC, behlendorf approved these changes
Would you mind rebasing this against the latest commits from master branch.

2022-11-28 19:50 UTC, amotin commented on cmd/zed/agents/zfs_mod.c
> +	(void) nvlist_lookup_uint64(nvl, ZPOOL_CONFIG_GUID, &guid);
@behlendorf That is why I asked him to initialize guid to zero above.

2022-11-28 20:01 UTC, behlendorf commented on cmd/zed/agents/zfs_mod.c
> +	(void) nvlist_lookup_uint64(nvl, ZPOOL_CONFIG_GUID, &guid);
Thanks.  I'm not sure why this comment ended up getting posted again, but I'm happy with the fix.

2022-11-29 00:51 UTC, tonyhutter approved these changes

2022-11-29 17:24 UTC, merged