Bugfix: Avoid a null pointer dereference in zfs_mount() on FreeBSD
openzfs/zfs pull request #14218
Opened 2022-11-23 01:55 UTC by allanjude

### Motivation and Context
Stop FreeBSD Panicing at boot when using ZFS as the root filesystem

### Description
When mounting the root filesystem, vfs_t->mnt_vnodecovered is null

This will cause zfsctl_is_node() to dereference a null pointer when mounting, or updating the mount flags, on the root filesystem, both of which happen during the boot process.

Reported-by: Martin Matuska <mm@FreeBSD.org>
Sponsored-by: Klara, Inc.
Signed-off-by: Allan Jude <allan@klarasystems.com>

### How Has This Been Tested?
Booting FreeBSD in a VM using openzfs.ko (master)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-11-23 13:19 UTC, szubersk approved these changes

2022-11-23 19:00 UTC, ryao requested changes

2022-11-23 19:00 UTC, ryao commented on module/os/freebsd/zfs/zfs_vfsops.c
> +	isctlsnap = (mvp != NULL && zfsctl_is_node(mvp) && strchr(osname, '@') != NULL);
There is a check style complaint about the line you changed. It needs to be wrapped.

2022-11-24 02:14 UTC, amotin approved these changes

2022-11-24 23:57 UTC, ryao approved these changes

2022-11-28 21:40 UTC, merged