Cleanup: Suppress some clang static analyzer defect reports
openzfs/zfs pull request #14470
Opened 2023-02-07 10:24 UTC by ryao

### Motivation and Context
Reducing the number of reports by Clang's static analyzer helps to uncover lingering bugs in the code that are hiding among the reports, such as #14469.

### Description
We mostly just add assertions. In the case of zfsdev_state_list, we could have used an assertion, but refactoring the code to statically allocate memory seemed better since that avoids the need for an assertion. It is probably not a terrible micro-optimization either, under the assumption that static allocation is faster than `kmem_alloc()`.

### How Has This Been Tested?
Build tests have been done.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2023-02-23 19:50 UTC, bwatkinson requested changes
Everything in this PR looks good to me. However, the commit message title:
`Suppress Clang static analyzer warning in dmu_objset_create_impl_dnstats()`
Breaks the style check of a commit title over 72 characters. Can you shorten the title of this commit?

2023-02-24 17:23 UTC, ryao commented
@bwatkinson I have changed the commit titles to shorten them, rebased on master and repushed.

2023-02-24 22:59 UTC, bwatkinson approved these changes

2023-02-28 00:01 UTC, ryao commented
I have rebased this on master and repushed.

2023-02-28 01:22 UTC, behlendorf approved these changes

2023-03-01 01:32 UTC, closed without merging