Minor: Remove unnecessary comma in zpool-create.8
openzfs/zfs pull request #15011
Opened 2023-06-24 20:01 UTC by Laevos

### Motivation and Context

Minor grammatical correction in the man page of `zpool-create(8)`, removes a comma which is not necessary in English.

### Description

Remove a comma from the warning about multiple simultaneous instances of zpool commands targeting the same device.

### How Has This Been Tested?

N/A

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2023-06-26 16:44 UTC, bwatkinson requested changes
This looks good to me. However, can you squash this down into just a single commit?

2023-06-26 19:13 UTC, Laevos commented
@bwatkinson Sure thing, updated!

2023-06-27 15:19 UTC, bwatkinson approved these changes

2023-06-27 17:00 UTC, behlendorf approved these changes

2023-06-27 23:58 UTC, merged