spa_min_alloc should be GCD, not min
openzfs/zfs pull request #15067
Opened 2023-07-13 18:20 UTC by ixhamza

### Motivation and Context

Since spa_min_alloc may not be a power of 2, unlike ashifts, in the case of DRAID, we should not select the minimal value among several vdevs. Rounding to a multiple of it is unlikely to work for other vdevs. Instead, using the greatest common divisor produces smaller yet more reasonable results.

### How Has This Been Tested?
```
# Create disks
truncate -s 256m /var/tmp/disk1
truncate -s 256m /var/tmp/disk2
truncate -s 256m /var/tmp/disk3
truncate -s 256m /var/tmp/disk4
truncate -s 256m /var/tmp/disk5

# Create a draid pool with ashift=9
echo 9 > /sys/module/zfs/parameters/vdev_file_logical_ashift
echo 9 > /sys/module/zfs/parameters/vdev_file_physical_ashift
zpool create tank draid1 /var/tmp/disk1 /var/tmp/disk2 /var/tmp/disk3 /var/tmp/disk4 -f

# spa_min_alloc will be 1536 [(vdc->vdc_ndata << vd->vdev_ashift) =>
# (3 << 512) => 1536]

# Add another top-level vdev with ashift=10, which produces min_alloc
# 1024 [(1 << ashift) => (1 << 10) => 1024] 
echo 10 > /sys/module/zfs/parameters/vdev_file_logical_ashift
echo 10 > /sys/module/zfs/parameters/vdev_file_physical_ashift
zpool add tank /var/tmp/disk5 -f

# New spa_min_alloc will now be 512 [gcd(1536, 1024) => 512] instead
# of 1024 [min(1536, 1024)] 
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2023-07-13 18:21 UTC, ixhamza commented
cc: @amotin

2023-07-13 18:26 UTC, amotin approved these changes

2023-07-13 18:32 UTC, amotin commented
For a note, in https://github.com/openzfs/zfs/pull/14909 I am rounding ZIL block allocation size to spa_min_alloc, and previous min value could result in allocation bigger than other vdev where allocation finally ended up can efficiently handle.

2023-07-13 18:48 UTC, amotin commented
Thinking more about it, I think we should both keep old min value and just add new gcd.  If allocation size is smaller than spa_min_alloc, then it should be set to spa_min_alloc and suffer whatever inefficiency happen on bigger vdev.  If allocation is bigger than spa_min_alloc, then we should use roundup(s, spa_agc_alloc).  We should probably add a function/macro implementing this logic.

2023-07-13 20:10 UTC, ixhamza commented
Thank you @amotin for the feedback. Updated.

2023-07-13 20:26 UTC, amotin requested changes

2023-07-13 20:26 UTC, amotin commented on module/zfs/vdev.c
> +			}
Why not make spa_min_alloc and spa_gcd_alloc logic completely separate.  Joined together it makes me worry about possible combinations.

2023-07-13 20:26 UTC, amotin commented on module/zfs/zio.c
> +
I meant something like this:
uint64_t
spa_min_alloc_size(spa_t *spa, uint64_t size)
{
    if (size > spa->spa_min_alloc)
        return (roundup(size, spa->spa_gcd_alloc))
    return (spa->spa_min_alloc)
}

2023-07-13 20:39 UTC, ixhamza commented
Thanks, @amotin. I will address your feedback.

2023-07-14 12:44 UTC, ixhamza commented on module/zfs/zio.c
> +			ASSERT3U(spa->spa_gcd_alloc, >=, SPA_MINBLOCKSIZE);
@amotin - could you please check this line? The ASSERT should be for `SPA_MINBLOCKSIZE` instead of `SPA_MINBLOCKSHIFT` if I'm not missing anything.

2023-07-14 14:04 UTC, amotin commented on module/zfs/zio.c
> + * Get allocation size.
This comment does not worth screen space it takes.  What would you say about: "Round provided allocation size up to a value that can be allocated by at least some vdev(s) in the pool with minimum or no additional padding and without extra space usage on others".

2023-07-14 16:55 UTC, ixhamza commented on module/zfs/zio.c
> +			ASSERT3U(spa->spa_gcd_alloc, >=, SPA_MINBLOCKSIZE);
Thank you, I have removed it.

2023-07-14 16:57 UTC, amotin approved these changes

2023-07-20 17:23 UTC, behlendorf approved these changes

2023-07-20 17:23 UTC, merged