linux/spl/kmem_cache: undefine `kmem_cache_alloc` before defining it
openzfs/zfs pull request #15144
Opened 2023-08-02 16:13 UTC by RaitoBezarius

### Motivation and Context

2.2 variant of #15143.

When compiling a kernel with bcachefs and zfs, the two macros will collide, making it impossible to have both filesystems.

It is sufficient to just undefine the macro before calling it.

On why this should be in ZFS rather than bcachefs, currently, bcachefs is not a in-tree filesystem, but, it has a reasonably high chance of getting included soon.

This avoids the breakage in ZFS early, this patch may be distributed downstream in NixOS and is already used there.### Description

### How Has This Been Tested?

I am not running 2.2 series yet.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2023-08-02 18:02 UTC, behlendorf approved these changes

2023-08-03 23:09 UTC, bwatkinson requested changes
This looks good to me, but you need to update your commit message with the sign off to fit into the coding style. Just do a `git commit --amend --signoff` and push back to this PR.

2023-08-03 23:15 UTC, RaitoBezarius commented
> This looks good to me, but you need to update your commit message with the sign off to fit into the coding style. Just do a `git commit --amend --signoff` and push back to this PR.

Oh yes sorry.

2023-08-07 15:30 UTC, bwatkinson approved these changes

2023-08-07 20:56 UTC, merged