Linux: Print to stderr when ZPOOL_IMPORT_UDEV_TIMEOUT_MS exceeded
openzfs/zfs pull request #15616
Opened 2023-11-30 22:19 UTC by ryao

### Motivation and Context
libudev support was added in 0.7.y and ever since, whenever udev is unavailable or something is wrong with it, pools take 30 seconds to import, which is extremely annoying to system administrators. There is no obvious sign of the problem, making it even more annoying. Let's report this condition to system administrators going forward.

### Description
If we hit the timeout, we print a message.

### How Has This Been Tested?
The buildbot can confirm it builds. Further testing is left to those affected by this problem. It is a trivial change.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2023-12-05 19:20 UTC, behlendorf commented
This change fails to build cleanly with `-Werror`.

```
lib/libzutil/os/linux/zutil_import_os.c: In function 'zpool_label_disk_wait':
lib/libzutil/os/linux/zutil_import_os.c:655:2: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
  } while (c = ((NSEC2MSEC(gethrtime() - start) < timeout_ms)));
  ```

2023-12-13 22:42 UTC, ryao commented
I thought I had fixed this before uploading it, but apparently, I did not. It is caused by a misplaced parenthesis:

```
diff --git a/lib/libzutil/os/linux/zutil_import_os.c b/lib/libzutil/os/linux/zutil_import_os.c
index 6574a4b74..42c4530d1 100644
--- a/lib/libzutil/os/linux/zutil_import_os.c
+++ b/lib/libzutil/os/linux/zutil_import_os.c
@@ -652,7 +652,7 @@ zpool_label_disk_wait(const char *path, int timeout_ms)
                udev_device_unref(dev);
                (void) usleep(sleep_ms * MILLISEC);
 
-       } while (c = ((NSEC2MSEC(gethrtime() - start) < timeout_ms)));
+       } while ((c = (NSEC2MSEC(gethrtime() - start) < timeout_ms)));
 
        if (c == B_FALSE)
                fprintf(stderr, "error: %s",
```

2023-12-13 22:48 UTC, ryao commented
I pushed one more revision to add a missing end of line '\n'. I caught this in self-review.

2023-12-13 23:18 UTC, behlendorf commented
You're going to need to rebase this on master as well.

2023-12-14 20:56 UTC, ryao commented
> You're going to need to rebase this on master as well.

Done

2023-12-15 17:59 UTC, behlendorf requested changes

2023-12-15 17:59 UTC, behlendorf commented on lib/libzutil/os/linux/zutil_import_os.c
> +		    "ZPOOL_IMPORT_UDEV_TIMEOUT_MS exceeded\n");
We should avoid printing to stderr/stdout from within the library.  Let's instead return `ETIMEDOUT` and update all the callers which are already logging the error as appropriate on failure.

2025-06-07 01:48 UTC, closed without merging