freebsd: fix bootstrapping tools under Linux/musl
openzfs/zfs pull request #15780
Opened 2024-01-16 18:08 UTC by valpackett

### Motivation and Context

musl libc has deprecated LFS64 aliases, so bootstrapping FreeBSD tools under musl distros has been failing with stat64 errors.

### Description

Apply the aliases under non-glibc Linux to fix this problem.

### How Has This Been Tested?

This is part of my work on making FreeBSD build under Chimera Linux; it builds :)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2024-01-17 21:01 UTC, behlendorf approved these changes
> This is part of my work on making FreeBSD build under Chimera Linux; it builds :)

That's pretty cool.  

Can you just address the `make cstyle` issue, then force update the PR.

2024-01-18 23:15 UTC, ryao requested changes
This should cause build failures on older versions of musl. We should use #ifundef as a guard against multiple definitions to avoid problems on them.

This also would likely cause build failures on systems using uclibc and klibc. At a glance, uclibc appears to mimic glibc while klibc is like musl, but defines these. I am not sure if anyone is using these libcs (or if we even build on them at present), but we probably should also include `!defined(__UCLIBC__)` in the linux check. klibc should not need an explicit check as long as it has the multiple definition protection meant for older musl libc versions.

2024-01-18 23:21 UTC, ryao commented
@behlendorf Boostrapping FreeBSD on other Linux libcs is likely broken in other places (since I doubt anyone ever does it), so it would not be terrible if merge this without minor corrections for the portability issues that I raised.

2024-01-19 21:00 UTC, behlendorf commented
@ryao I fully expect there are other compatibility issues out there lurking.  We'll have to fix those as they're encountered.

2024-01-19 21:01 UTC, merged