zpool status: Fix option string, adding -e and fixing order
openzfs/zfs pull request #16008
Opened 2024-03-18 21:14 UTC by cmharr

### Motivation and Context

Fixes missing `zpool status help` option and alphabetizes the options

Issue #16004 

### Description

The recently added '-e' option (PR #15769) missed adding the new option in the online `zpool status` help command. This adds the option and reorders the 'i' and 'D' options alphabetically.

### How Has This Been Tested?

Test new online help menu:
Before:
```
[root@iron5:zfs2.2]# ./zpool status -h
invalid option 'h'
usage:
	status [--power] [-c [script1,script2,...]] [-igLpPstvxD]  [-T d|u] [pool] ... 
	    [interval [count]]
```
After:
```
[root@iron5:zfs2.2]# ./zpool status -h
invalid option 'h'
usage:
	status [--power] [-c [script1,script2,...]] [-DegiLpPstvx]  [-T d|u] [pool] ... 
	    [interval [count]]
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [] I have updated the documentation accordingly.
- [] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

Signed-off-by: Cameron Harr harr1@llnl.gov

2024-03-18 23:58 UTC, bwatkinson requested changes
Just a little bit of OCD on my part, but can you also update `zpool-status.8` to also have the options list in alphabetical order as well as part of the PR? They are in line 39 of that file.

2024-03-19 15:22 UTC, cmharr commented
@bwatkinson, I *think* I got all the places in `zpool status` with the wrong order. Thanks for  pointing out where it still needed an edit.

2024-03-19 16:26 UTC, bwatkinson commented
> @bwatkinson, I _think_ I got all the places in `zpool status` with the wrong order. Thanks for pointing out where it still needed an edit.

Cool and thanks. Also can you look into the CI test failures for:
```
    FAIL cli_root/zpool_status/zpool_status_001_pos (expected PASS)
    FAIL cli_root/zpool_status/zpool_status_002_pos (expected PASS)
    FAIL cli_user/misc/zpool_001_neg (expected PASS)
 ```
 Those seem to reliably fail with this PR.

2024-03-20 23:31 UTC, behlendorf approved these changes

2024-03-21 15:45 UTC, bwatkinson approved these changes

2024-03-21 16:00 UTC, merged