Make sure avl_tree.avl_pad is not in kernel module
openzfs/zfs pull request #16280
Opened 2024-06-18 15:05 UTC by youzhongyang

Make sure avl_tree.avl_pad is not in kernel module.

### Motivation and Context

The commit b192a2c0a19133234972b491e9c06093b3d21358 (Remove avl_size field from struct avl_tree) uses a def _KERNEL to decide to include avl_pad or not, but this _KERNEL is defined in sys/sysmacros.h. If avl.h and sysmacros.h are not included in the right order, it can cause a headache when working on a zfs related kernel module.

### Description

This PR changes avl_impl.h to use ```__KERNEL__``` instead of _KERNEL, it also moves avl.h after sysmacros.h in spa.h.

### How Has This Been Tested?

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2024-06-18 15:08 UTC, youzhongyang commented
@amotin - Could you please take a look? thanks.

2024-06-18 15:16 UTC, amotin requested changes
We do not use `__KERNEL__` almost anywhere now.  Lets keep it as `_KERNEL` here.  Moving `sysmacros.h` include up looks right to me and I think should be sufficient.

2024-06-18 15:45 UTC, amotin reviewed
Thinking again, it would be safer to add sys/sysmacros.h directly inside avl_impl.h to reduce implicit dependencies.

2024-06-18 16:10 UTC, amotin reviewed
What makes me wonder is why in `spa.h` `avl.h` is included before `zfs_context.h`.  As I see, `zfs_context.h` already includes `sysmacros.h`, so it may be redundant.

2024-06-18 16:25 UTC, youzhongyang commented
> What makes me wonder is why in `spa.h` `avl.h` is included before `zfs_context.h`. As I see, `zfs_context.h` already includes `sysmacros.h`, so it may be redundant.

I agree, no need to change the order of includes in spa.h if sysmacros.h is added in avl_impl.h, or to make more sense, move "#include <sys/zfs_context.h>" before "#include <sys/avl.h>" and remove "#include <sys/sysmacros.h>" from spa.h.

2024-06-25 00:15 UTC, robn approved these changes
Looks fine. Can you just clean up the commit list a bit, four commits for a +2/-2 is a bit much now heh :)

2024-06-28 18:41 UTC, amotin approved these changes

2024-07-16 20:01 UTC, mcmilk approved these changes

2024-07-16 23:02 UTC, tonyhutter commented
Can you update your commit message to remove the duplicate Signed-off-by lines, and add in the description text from this PR?  So like:
```
Make sure avl_tree.avl_pad is not in kernel module

The commit b192a2c (Remove avl_size field from struct avl_tree) uses a
def _KERNEL to decide to include avl_pad or not, but this _KERNEL is
defined in sys/sysmacros.h. If avl.h and sysmacros.h are not included
in the right order, it can cause a headache when working on a zfs
related kernel module.

Remove sysmacros.h from spa.h to fix.

Signed-off-by: Youzhong Yang <yyang@mathworks.com>
```

2024-07-17 02:18 UTC, youzhongyang commented
> Can you update your commit message to remove the duplicate Signed-off-by lines, and add in the description text from this PR? So like:
> 
> ```
> Make sure avl_tree.avl_pad is not in kernel module
> 
> The commit b192a2c (Remove avl_size field from struct avl_tree) uses a
> def _KERNEL to decide to include avl_pad or not, but this _KERNEL is
> defined in sys/sysmacros.h. If avl.h and sysmacros.h are not included
> in the right order, it can cause a headache when working on a zfs
> related kernel module.
> 
> Remove sysmacros.h from spa.h to fix.
> 
> Signed-off-by: Youzhong Yang <yyang@mathworks.com>
> ```

Thanks. Rebased and force updated.

2024-07-17 20:51 UTC, tonyhutter approved these changes

2024-07-17 20:54 UTC, merged