rpm: dkms: Include other kernel-devel packages for spec requirements
openzfs/zfs pull request #16894
Opened 2024-12-21 12:16 UTC by niclimcy

### Motivation and Context
- Fedora users who use LTS kernels depend on a different kernel-devel package (kernel-longterm-devel).
- Similarly, Fedora Asahi Linux users use kernel-16k-devel instead of kernel-devel
- Update spec requirements to include both kernel-devel packages to support these set-ups.
- Should address #16742 and #16429

### Description
- Replace `Requires`, `Requires(post)`, and `Conflicts` with boolean operators according to https://rpm-software-management.github.io/rpm/manual/boolean_dependencies.html

### How Has This Been Tested?
- Can't seem to build the zfs-dkms rpm packages according to this documentation: https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html#dkms , seem to only get src packages instead.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2024-12-21 20:46 UTC, JMOdero commented on rpm/generic/zfs-dkms.spec.in
**Are we sure about the use of "and" in lines 33-35?**  That didn't seem to work for me.  I deleted those "ands" and just left one blank space between the "or" boolean statements.... Requires:  (x or y or z) (a or b or c)

2024-12-27 19:44 UTC, JMOdero commented
I haven't had time to test the "Conflicts:" line.  As I previously mentioned openzfs compiled and installed fine without it on my system.

However, I'm wondering if something like this would be better if you wish to include it...

`Conflicts: (kernel-devel and kernel-longterm-devel) (kernel-devel and kernel-16k-devel) ( kernel-longterm-devel and kernel-16k-devel)`

As far as "Conflicts:" goes I don't think we need to get into specific versions ranges.

2024-12-27 20:56 UTC, AllKind requested changes

2024-12-27 20:56 UTC, AllKind commented on rpm/generic/zfs-dkms.spec.in
> +Conflicts:      (kernel-devel >= @ZFS_META_KVER_MIN@ or kernel-longterm-devel >= @ZFS_META_KVER_MIN@ or kernel-16k-devel >= @ZFS_META_KVER_MIN@) and (kernel-devel <= @ZFS_META_KVER_MAX@.999 or kernel
```suggestion
Conflicts:      (kernel-devel < @ZFS_META_KVER_MIN@ or kernel-longterm-devel < @ZFS_META_KVER_MIN@ or kernel-16k-devel < @ZFS_META_KVER_MIN@) and (kernel-devel > @ZFS_META_KVER_MAX@.999 or kernel-longterm-devel > @ZFS_META_KVER_MAX@.999 or kernel-16k-devel > @ZFS_META_KVER_MAX@.999)
```

2024-12-27 20:56 UTC, AllKind commented on rpm/generic/zfs-dkms.spec.in
> +Conflicts:      (kernel-devel >= @ZFS_META_KVER_MIN@ or kernel-longterm-devel >= @ZFS_META_KVER_MIN@ or kernel-16k-devel >= @ZFS_META_KVER_MIN@) and (kernel-devel <= @ZFS_META_KVER_MAX@.999 or kernel
You created a false conflict logic, which will not allow any valid kernel version.
Maybe that's why you are not able to build the rpm packages.

2024-12-27 20:58 UTC, AllKind commented
> As far as "Conflicts:" goes I don't think we need to get into specific version ranges.

Of course the versions are needed. You cannot install onto a no longer, or not yet supported kernel version.

2024-12-28 01:20 UTC, JMOdero commented
> > As far as "Conflicts:" goes I don't think we need to get into specific version ranges.
> 
> Of course the versions are needed. **You cannot install onto a no longer, or not yet supported kernel version.**

**Yes, but don't the "Requires:" and "Requires(post):" take care of that?**

Like I said before the compile and install worked fine without the conflicts line, and as far as I know with my _very_ limited knowledge openzfs never needed a "Conflicts:" line before in that spec file.

I'm new to all this so I could be very wrong, but isn't the "conflict" that we are concerned about at that stage, using two or more of kernel-devel, kernel-longterm-devel, or kernel-16k-devel when one of a different "flavor" is already in use?

**So like my code suggests we are checking to see if we are using say kernel-16k-devel of ANY version and if so then kernel-devel of ANY version is a conflict.**  At that stage the version is not an issue.  If say ANY kernal-longterm-devel is installed then we don't want to install kernel-devel nor kernel-16k-devel of ANY version.

`Conflicts: (kernel-devel and kernel-longterm-devel) (kernel-devel and kernel-16k-devel) (kernel-longterm-devel and kernel-16k-devel)`

2024-12-29 21:56 UTC, AllKind commented
>         As far as "Conflicts:" goes I don't think we need to get into specific version ranges.
> 
>     Of course the versions are needed. You cannot install onto a no longer, or not yet supported kernel version.
> 
> Yes, but don't the "Requires:" and "Requires(post):" take care of that?

There is also the cases where kernel updates to a not yet supported version lead to ZFS being uninstalled and users had no access to their filesystems any more.

Regarding the "flavors":
AFAIK the longterm kernel isn't an official fedora thing. But still would be nice to support I guess. Also there is a high probability  they are install along "regular" kernels.
Asahi is a fedora based distro. I have no idea what the chances are the 16k kernel being installed alongside a "regular" kernel. That's why I wrote in the issue tracker that there seems to be no `%asahi` macro defined and if seemed necessary to differentiate it in the rpm .spec, `%dist_vendor` or similar would need to be used.

In regards to the syntax, I have no opinion whether to use `and`, `comma` or simple `space`. As long the logic is correct and it works.

2025-08-11 05:43 UTC, closed without merging